isa_search_customization.settings:
  type: config_object
  label: 'ISA Search Customization Settings'
  mapping:
    basic_auth_credentials:
      type: string
      label: 'Basic Auth Credentials (Base64 encoded)'
    allowed_scraping_hosts:
      type: sequence
      label: 'Allowed hosts for content scraping'
      sequence:
        type: string